# Don't store sensitive data in this file
# Use env vars in docker-compose.override.yml (ignored by Git) instead
version: '3.9'
services:
  app-blue:
    image: ${APP_IMAGE:?}
    container_name: pocketo-app-blue
    depends_on:
      - db
      - cache
    environment:
      - RUN_VIA_DOCKER_COMPOSE=1
  app-green:
    extends:
      service: app-blue
    container_name: pocketo-app-green
  db:
    image: 'postgres:15-alpine'
    container_name: pocketo-db
  cache:
    image: 'redis:7-alpine'
    container_name: pocketo-cache
