# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Development CI/CD

on:
  push:
    branches: [ "setup/ci-cd" ]
  pull_request:
    branches: [ "setup/ci-cd" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        gradle-version: wrapper
    - name: Run Gradle checking tasks
      run: ./gradlew check # Includes checkFormat, test,...
    - name: Build Docker image
      run: ./gradlew dockerImageBuild -PimageTag="dev-${GITHUB_SHA::7}"
    - name: Log in to Docker registry
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Push Docker image
      run: ./gradlew dockerImagePush -PimageTag="dev-${GITHUB_SHA::7}"
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          password: ${{ secrets.TEST_SERVER_PASSWORD }}
          port: ${{ secrets.TEST_SERVER_PORT }}
          script: echo "dev-${GITHUB_SHA::7}"
